### PR TITLE
Thank you page values and instalments fixed

### LINKED ISSUE #466: Thank you pages with readable values
Show the order valures more readable for the users, because actually the plugin shows the order amount with stranger number format.

### PR DESCRIPTION
**Pull request by cezarlz**
Closes #466

### CODE REVIEW

File: woocommerce-gateway-ebanx/templates/ebanx-credit-card-mx/payment-processing.php [hunk 1]
```diff
@@ -14,7 +14,7 @@
 
 <p><strong><?php _e(sprintf('Pago aprobado con éxito, %s.', $customer_name), 'woocommerce-gateway-ebanx') ?></strong></p>
 <p><strong><?php _e('Resumo de la compra:', 'woocommerce-gateway-ebanx') ?></strong></p>
-<p><?php _e('Valor:', 'woocommerce-gateway-ebanx') ?> <?php echo WC_EBANX_Constants::CURRENCY_CODE_USD ?> <?php echo $order_amount ?></p>
+<p><?php _e('Valor:', 'woocommerce-gateway-ebanx') ?> <?php echo $total ?></p>
 <?php if ($instalments_number > 1) : ?>
     <p><?php echo $instalments_number ?> <?php _e('meses sen intereses de', 'woocommerce-gateway-ebanx') ?> <?php WC_EBANX_Constants::CURRENCY_CODE_USD ?> <?php echo $instalments_amount ?></p>
```
Comment (SparK-Cruz) [inline woocommerce-gateway-ebanx/templates/ebanx-credit-card-mx/payment-processing.php]: Still USD without echo and not using site currency
