### PR TITLE
Resolves wp error to array

### LINKED ISSUE #365: Fatal error: Cannot use object of type WP_Error as array

### PR DESCRIPTION
**Pull request by gpressutto5**
Resolves #365

### CODE REVIEW

File: woocommerce-gateway-ebanx/woocommerce-gateway-ebanx.php [hunk 1]
```diff
@@ -274,6 +274,9 @@ public function my_account_endpoint()
 		public static function save_merchant_infos() {
 			// Save merchant informations
 			$user = get_userdata(get_current_user_id());
+			if (!user || is_wp_error($user)) {
```
Comment (cezarlz) [inline woocommerce-gateway-ebanx/woocommerce-gateway-ebanx.php]: It's missing the `$` on `user`. The correct is: `!$user`

File: CHANGELOG.md [hunk 2]
```diff
@@ -1,5 +1,8 @@
 # CHANGELOG
 
+## 1.6.2
+* Fix - Resolves fatal error when the plugin can't get the current user [#365](https://github.com/ebanx/woocommerce-gateway-ebanx/pull/365)
```
Comment (cezarlz) [inline CHANGELOG.md]: We don't know if the problem is really the current user... Can we change this message?

File: woocommerce-gateway-ebanx/woocommerce-gateway-ebanx.php (hunk 1 above)
Comment (gpressutto5) [inline woocommerce-gateway-ebanx/woocommerce-gateway-ebanx.php]: lol 😆

File: CHANGELOG.md (hunk 2 above)
Comment (gpressutto5) [inline CHANGELOG.md]: This fix will only work if the error is really the current user, otherwise it's not a fix. So i think it's ok to say this fix works when the plugin can't get the current user.

Comment (cezarlz) [inline CHANGELOG.md]: Fix - Resolves fatal error when the plugin can't get some informations. What do you think?
