### PR TITLE
Fixed compliance fields when country is empty

### LINKED ISSUE #497: Select country on checkout shows all compliance fields
## Expected behavior and actual behavior.
At checkout page, when a country is selected, the compliance fields works fine, but when the option is "Select a country..." all compliance fields show!

## Steps to reproduce the problem.
Go to checkout page, at Country field, select the option "Select a country..." (The first option).

## Specifications like the version of the project, operating system, or hardware.
v1.12.1

### PR DESCRIPTION
**Pull request by cezarlz**
Closes #497

### CODE REVIEW

File: woocommerce-gateway-ebanx/assets/js/checkout-fields.js [hunk 1]
```diff
@@ -65,10 +65,15 @@ jQuery (function ($) {
 
   $('#billing_country')
     .on('change',function() {
+      var country = this.value.toLowerCase();
```
Comment (SparK-Cruz) [inline woocommerce-gateway-ebanx/assets/js/checkout-fields.js]: Will value always be defined? Batshit crazy js stuff dude

Comment (cezarlz) [inline woocommerce-gateway-ebanx/assets/js/checkout-fields.js]: Yes, because #billing_country is a required field of WooCommerce.
